// THIS FILE WILL BE OVERWRITTEN BY DEV-C++!
// DO NOT EDIT!

#ifndef TORCS-CAR-SETUP-EDITOR_PRIVATE_H
#define TORCS-CAR-SETUP-EDITOR_PRIVATE_H

// VERSION DEFINITIONS
#define VER_STRING	"0.1.1.1"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	1
#define COMPANY_NAME	"TORCS Car Setup Editor"
#define FILE_VERSION	"beta 0.1"
#define FILE_DESCRIPTION	"Visual editor for TORCS created by Vicente Marti"
#define INTERNAL_NAME	"TORCS Car Setup Editor"
#define LEGAL_COPYRIGHT	"GNU GENERAL PUBLIC LICENSE, Version 2, June 1991"
#define LEGAL_TRADEMARKS	"None"
#define ORIGINAL_FILENAME	"TORCS Car Setup Editor"
#define PRODUCT_NAME	"TORCS Car Setup Editor"
#define PRODUCT_VERSION	"beta 0.1"

#endif //TORCS-CAR-SETUP-EDITOR_PRIVATE_H
